
alter table PISCINE DROP COLUMN TYP_ID;
alter table PISCINE DROP COLUMN PIS_CP;
alter table PISCINE ADD COLUMN CPI_CODEINSEE VARCHAR(5) not null;
alter table PISCINE ADD COLUMN PIS_DATEMAJ timestamp not null ;
alter table PISCINE ALTER COLUMN pis_nom TYPE VARCHAR(120);
alter table PISCINE ALTER COLUMN pis_adr TYPE VARCHAR(120);
DROP table TYPE_PISCINE;


